-- Sovereign app: base schema
-- Profiles, assets, session_logs, app_state. Run after creating a Supabase project.

-- Profiles (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Assets (mandates)
create table if not exists public.assets (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  category text not null check (category in ('personal','professional','vitality','capital')),
  priority text not null check (priority in ('high','medium','low')),
  target_hours numeric not null default 0,
  invested_hours numeric not null default 0,
  horizon_years smallint not null check (horizon_years in (1,5,10)),
  daily_tasks jsonb default '[]'::jsonb,
  critical_rituals text[] default '{}',
  created_at timestamptz default now()
);

alter table public.assets enable row level security;
drop policy if exists "Users can CRUD own assets" on public.assets;
create policy "Users can CRUD own assets" on public.assets for all using (auth.uid() = user_id);

-- Session logs (focus sessions)
create table if not exists public.session_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  asset_id uuid,
  asset_name text not null,
  duration_min int not null default 0,
  timestamp timestamptz not null,
  mode text not null check (mode in ('passive','focus'))
);

alter table public.session_logs enable row level security;
drop policy if exists "Users can CRUD own session_logs" on public.session_logs;
create policy "Users can CRUD own session_logs" on public.session_logs for all using (auth.uid() = user_id);

-- App state (vitals, life_tracker, playbook, etc.) per user per day
create table if not exists public.app_state (
  user_id uuid references auth.users on delete cascade not null,
  last_date text not null,
  vitals jsonb default '{}'::jsonb,
  life_tracker jsonb default '{}'::jsonb,
  ritual_definitions jsonb,
  pillar_rituals_config jsonb default '{}'::jsonb,
  completed_block_indices int[] default '{}',
  current_block_index int,
  current_block_suggested_minutes int,
  updated_at timestamptz default now(),
  primary key (user_id, last_date)
);

alter table public.app_state enable row level security;
drop policy if exists "Users can CRUD own app_state" on public.app_state;
create policy "Users can CRUD own app_state" on public.app_state for all using (auth.uid() = user_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
